In [46]:
# Import required modules
import pandas as pd
import numpy as np
from statsmodels.formula.api import logit

# Start coding!
car_insurance = pd.read_csv("car_insurance.csv")
display(car_insurance.head())
print(car_insurance.info())

       id  age  gender  ... duis past_accidents outcome
0  569520    3       0  ...    0              0     0.0
1  750365    0       1  ...    0              0     1.0
2  199901    0       0  ...    0              0     0.0
3  478866    0       1  ...    0              0     0.0
4  731664    1       1  ...    0              1     1.0

[5 rows x 18 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   10000 non-null  int64
 1   age                  10000 non-null  int64
 2   gender               10000 non-null  int64
 3   driving_experience   10000 non-null  object
 4   education            10000 non-null  object
 5   income               10000 non-null  object
 6   credit_score         9018 non-null   float64
 7   vehicle_ownership    10000 non-null  float64
 8   vehicle_year         10000 non-null  object
 9   married              10000 non-null  float64
 10  children             10000 non-null  float64
 11  postal_code          10000 non-null  int64
 12  annual_mileage       9043 non-null   float64
 13  vehicle_type         10000 non-null  object
 14  speeding_violations  10000 non-null  int64
 15  duis                 10000 non-null  int64
 16  past_accidents       10000 non-null  int64
 17  outcome              10000 non-null  float64
dtypes: float64(6), int64(7), object(5)
memory usage: 1.4+ MB
None

In [47]:
# handling missing data
car_insurance.credit_score.fillna(car_insurance.credit_score.mean(),inplace=True)
car_insurance.annual_mileage.fillna(car_insurance.annual_mileage.mean(),inplace=True)
print(car_insurance.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   10000 non-null  int64
 1   age                  10000 non-null  int64
 2   gender               10000 non-null  int64
 3   driving_experience   10000 non-null  object
 4   education            10000 non-null  object
 5   income               10000 non-null  object
 6   credit_score         10000 non-null  float64
 7   vehicle_ownership    10000 non-null  float64
 8   vehicle_year         10000 non-null  object
 9   married              10000 non-null  float64
 10  children             10000 non-null  float64
 11  postal_code          10000 non-null  int64
 12  annual_mileage       10000 non-null  float64
 13  vehicle_type         10000 non-null  object
 14  speeding_violations  10000 non-null  int64
 15  duis                 10000 non-null  int64
 16  past_accidents       10000 non-null  int64
 17  outcome              10000 non-null  float64
dtypes: float64(6), int64(7), object(5)
memory usage: 1.4+ MB
None

In [48]:
def model_accuracy(df):
    """
        this function builds a logistic regression model and calculates the accuracy
        
        Return the Accuracy
        
        NOTES :
            the first column has to be the explanatory variable
            the sacond column has to be the response variable
    """
    from statsmodels.formula.api import logit
    formula = df.columns[1] + " ~ " + df.columns[0]
    model = logit(formula=formula, data=df).fit()
    
    conf_matrix = model.pred_table()
    TN = conf_matrix[0,0]
    TP = conf_matrix[1,1]
    FN = conf_matrix[1,0]
    FP = conf_matrix[0,1]
    
    acc = (TN + TP) / (TN + TP + FN + FP)
    return acc

In [49]:
accuracy = {}
for i in car_insurance.columns[1:-1]:
    accuracy.update({i:model_accuracy(car_insurance[[i,"outcome"]])})
    
print(accuracy)

Optimization terminated successfully.
         Current function value: 0.511794
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.615951
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.467092
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.603742
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.531499
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.572557
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.552412
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.572668
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.586659
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.595431
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.617345
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.605716
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.621700
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.558922
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.598699
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.549220
         Iterations 7
{'age': 0.7747, 'gender': 0.6867, 'driving_experience': 0.7771, 'education': 0.6867, 'income': 0.7425, 'credit_score': 0.7054, 'vehicle_ownership': 0.7351, 'vehicle_year': 0.6867, 'married': 0.6867, 'children': 0.6867, 'postal_code': 0.6867, 'annual_mileage': 0.6904, 'vehicle_type': 0.6867, 'speeding_violations': 0.6867, 'duis': 0.6867, 'past_accidents': 0.6867}

In [50]:

df = pd.DataFrame.from_dict(accuracy,orient='index', columns=["accuracy"])\
.reset_index().sort_values(by="accuracy", ascending=False)

print(df)

                  index  accuracy
2    driving_experience    0.7771
0                   age    0.7747
4                income    0.7425
6     vehicle_ownership    0.7351
5          credit_score    0.7054
11       annual_mileage    0.6904
1                gender    0.6867
3             education    0.6867
7          vehicle_year    0.6867
8               married    0.6867
9              children    0.6867
10          postal_code    0.6867
12         vehicle_type    0.6867
13  speeding_violations    0.6867
14                 duis    0.6867
15       past_accidents    0.6867

In [51]:

best_feature_df = pd.DataFrame({"best_feature":["driving_experience"],"best_accuracy":[0.7771]})

display(best_feature_df)

         best_feature  best_accuracy
0  driving_experience         0.7771